### ISSUE TITLE
Week 1 review

### ISSUE THREAD

**Issue by otagi** [codelawer/hyf-html-css#1]
Gradients, custom fonts, animated logos, grids! You're already at week 3. 😛 

Congratulations, that's good work.

Some comments on the HTML file:

- There is a `<script src="main.js">` tag, but the file does not exist. It still works just fine, but there are a couple of reasons why it's better to remove the tag: the browser will still try to find the JS file, which will trigger an additional network request for your visitors. And as a rule of thumb, it's always better to remove code you don't need. This way, you won't ask yourself in 6 months "why is it there?". 😉 
- Small typo in one of the URLs: `http:\\google.com` instead of `http://google.com`.
- if your `section` and `article` tags are meant to be displayed on every page of your website, they're fine there. Otherwise, they can go inside the `main` tag, for a better semantic structure.
- The `p` tag with the copyright text is inside an `ul` tag. This is not permitted in HTML5. An `ul` tag can only have `li` tags as immediate children.

And the CSS file:

- Lots of advanced stuff, and good syntax. My only remark would be to shift all lines to the left, so that you don't have unnecessary spaces in front of these lines. Keep the good indentation for the content of the `{ }`, of course. 😉 

Happy coding!

**Comment by codelawer** [comment]
Thank you for your comments.
